<?php

namespace Database\Seeders;

use App\Models\ContentBlock;
use Illuminate\Database\Seeder;

class ContentBlockSeeder extends Seeder
{
    /**
     * Seed the service pages' article content as editable blocks.
     *
     * Non-destructive: a page is only populated when it currently has NO
     * blocks. Pages the admin has already added to or edited are left
     * untouched, so running this seeder never wipes admin changes. This
     * makes it safe to run on every deploy to fill in any empty pages.
     *
     * To intentionally reset a page back to these defaults, delete its
     * blocks in the admin panel (or the DB) first, then re-run the seeder.
     */
    public function run(): void
    {
        $pages = [
            'heating' => $this->heating(),
            'cooling' => $this->cooling(),
            'plumbing' => $this->plumbing(),
            'electrical' => $this->electrical(),
            'indoor-air-quality' => $this->airQuality(),
            'drains' => $this->drains(),
            'commercial' => $this->commercial(),
        ];

        foreach ($pages as $page => $blocks) {
            // Skip any page that already has content — preserves admin edits.
            if (ContentBlock::where('page', $page)->exists()) {
                continue;
            }

            foreach ($blocks as $i => $block) {
                ContentBlock::create(array_merge($block, ['page' => $page, 'position' => $i]));
            }
        }
    }

    private function heating(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Furnace Repair in NJ', 'body' => "When your furnace quits on a freezing January night, you need furnace repair in NJ that shows up fast and gets it right the first time. Guardian Air is a licensed and insured heating company serving homeowners across Monmouth, Middlesex, and Ocean counties with same-day furnace repair, honest diagnostics, and upfront, flat-rate pricing — no overtime surprises and no pressure.\n\nOur technicians repair every make and model of gas, electric, and oil furnace. From a furnace that blows cold air or short-cycles to a unit that won't ignite at all, we pinpoint the real problem — a failed igniter, flame sensor, blower motor, control board, or gas valve — and fix it on the spot whenever possible. Because we stock common parts on every truck, most repairs are completed in a single visit.\n\nEvery furnace repair starts with a clear explanation of what's wrong and what it will cost, so you can make an informed decision before any work begins. It's heating service the way it should be: fast, fair, and done by a local team your neighbors already trust."],
            ['type' => 'section', 'heading' => 'Why Furnace Maintenance Matters', 'body' => "Most no-heat emergencies are preventable. A short annual furnace tune-up protects your comfort, your safety, and your wallet all winter long.\n\nPrevent Unexpected Breakdowns — Regular inspections catch worn parts and small problems early, before they turn into a no-heat emergency on the coldest night of the year.\n\nImprove Energy Efficiency — A clean, well-tuned furnace burns less fuel to keep your home warm, lowering your monthly utility bills throughout the New Jersey heating season.\n\nExtend Equipment Lifespan — Consistent maintenance keeps your system running longer, delaying the cost of a full replacement by years and protecting your manufacturer's warranty.\n\nProtect Your Family's Safety — A maintenance visit includes a carbon monoxide and heat-exchanger check, so you can run your furnace with peace of mind. We recommend scheduling your tune-up in early fall, before the first cold snap."],
            ['type' => 'image', 'heading' => 'Guardian Air technician performing furnace repair in a New Jersey home', 'image_path' => '/img/heating-hero.webp'],
            ['type' => 'section', 'heading' => 'When to Replace Your Furnace', 'body' => "Deciding whether to repair or replace your furnace can be tough. These signs usually mean replacement is the smarter long-term investment.\n\nAge — If your furnace is more than 15 years old, it's far less efficient than modern units and more prone to failure. Newer high-efficiency systems can noticeably cut your heating bills.\n\nFrequent Repairs — If you're calling for furnace repair every season, the repair costs often add up to more than a reliable new system would cost.\n\nUneven or Weak Heat — Cold spots and rooms that never warm up properly are a sign your furnace can no longer keep up with your home's demand.\n\nRising Energy Bills — An unexplained jump in heating costs usually means your furnace is losing efficiency as it wears out.\n\nNot sure which way to go? We'll give you an honest assessment and a free replacement estimate — never a hard sell."],
            ['type' => 'section', 'heading' => 'Heating Systems We Service', 'body' => "Our licensed technicians install, repair, and maintain every major type of home heating system across New Jersey.\n\nGas Furnaces — The most common and cost-effective option, burning natural gas for fast, powerful, whole-home heat.\n\nOil Furnaces — Common in older New Jersey homes, delivering strong, reliable heat output; we service and tune oil systems of every age.\n\nElectric Furnaces — A great fit for homes without a gas line, using electric heating elements for clean, simple heat.\n\nHeat Pumps — Energy-efficient electric systems that both heat and cool, ideal for year-round comfort and lower operating costs.\n\nBoilers — Steady radiant warmth through hot water, feeding radiators or in-floor heating; we repair leaks, pressure problems, and no-heat issues."],
            ['type' => 'section', 'heading' => 'No-Heat Emergency Service 24/7', 'body' => "A heating failure in the middle of a New Jersey winter isn't something that can wait until morning. That's why Guardian Air offers 24/7 no-heat emergency furnace repair across Monmouth, Middlesex, and Ocean counties.\n\nWhen you call, you reach a real person who dispatches a licensed technician fast — fully stocked to handle most repairs on the first visit. Whether it's a failed igniter, a tripped safety switch, or a furnace that simply won't turn on, we restore your heat quickly and safely.\n\nAnd because our pricing is flat-rate, you'll never pay extra for nights, weekends, or holidays. Honest emergency service when you need it most."],
            ['type' => 'section', 'heading' => 'Serving Monmouth, Middlesex & Ocean County', 'body' => "Guardian Air provides trusted furnace repair and heating service to homeowners throughout central New Jersey. Our technicians are local, which means faster response times and a team that knows the older oil systems and newer high-efficiency furnaces common to the area.\n\nWe proudly serve Toms River, Freehold, Brick, Old Bridge, Red Bank, and Lakewood, along with surrounding communities across all three counties. From the Ocean County shore to the neighborhoods of Middlesex and Monmouth, the same trusted technicians keep your home warm.\n\nDon't see your town listed? We almost certainly still serve it — give us a call to confirm and schedule your furnace repair or tune-up today."],
            ['type' => 'faq', 'heading' => 'How much does furnace repair cost in NJ?', 'body' => 'Most furnace repairs in New Jersey fall between $150 and $750 depending on the failed part — an igniter or flame sensor is on the lower end, while a blower motor or control board is higher. We always provide a flat-rate quote before any work begins, so you know the full cost upfront with no surprises.'],
            ['type' => 'faq', 'heading' => 'When should I replace my furnace instead of repairing it?', 'body' => 'Replacement usually makes sense when your furnace is over 15 years old, needs frequent or expensive repairs, heats unevenly, or is driving up your energy bills. If a single repair is minor and the system is otherwise healthy, fixing it is the better value. We give you an honest recommendation either way.'],
            ['type' => 'faq', 'heading' => 'Why does my furnace keep shutting off?', 'body' => 'Short-cycling is most often caused by a dirty air filter restricting airflow, a malfunctioning thermostat, a clogged flue, or an overheating safety switch doing its job. A quick diagnostic visit pinpoints the exact cause and prevents further wear on the system.'],
            ['type' => 'faq', 'heading' => 'Should I choose an oil or gas furnace?', 'body' => 'Gas furnaces are typically cheaper to run and lower-maintenance where a natural gas line is available, which is why most New Jersey homeowners choose them. Oil furnaces remain a strong option for homes without gas service and can deliver very high heat output. We help you compare based on your home and local fuel costs.'],
            ['type' => 'faq', 'heading' => 'How long does a furnace installation take?', 'body' => 'A standard furnace replacement is usually completed in a single day — typically four to eight hours. More involved jobs, such as switching fuel types or modifying ductwork, may take longer. We give you a clear timeline with your free estimate.'],
            ['type' => 'faq', 'heading' => 'What areas do you serve for furnace repair?', 'body' => 'We provide furnace repair and heating service across Monmouth, Middlesex, and Ocean counties, including Toms River, Freehold, Brick, Old Bridge, Red Bank, Lakewood, and the surrounding towns. Call us to confirm service to your specific address.'],
        ];
    }

    private function cooling(): array
    {
        return [
            ['type' => 'section', 'heading' => 'AC Repair in NJ', 'body' => "When your air conditioner blows warm air in the middle of a July heatwave, you need AC repair in NJ that responds fast and fixes it right. Guardian Air is a licensed and insured cooling company serving homeowners across Monmouth, Middlesex, and Ocean counties with same-day air conditioning repair, honest diagnostics, and upfront, flat-rate pricing — no overtime fees and no pressure.\n\nWe repair every major brand of central air, heat pump, and ductless system. Whether your AC won't turn on, short-cycles, leaks water, or simply can't keep up, our technicians pinpoint the real cause — a failed capacitor, low refrigerant, a dirty coil, a bad contactor, or a struggling compressor — and fix it on the spot whenever possible. Most repairs are completed in a single visit because we stock common parts on every truck.\n\nEvery repair begins with a clear explanation of the problem and a flat-rate quote, so you know the cost before we start. It's cooling service the way it should be: fast, fair, and backed by a local team your neighbors trust."],
            ['type' => 'section', 'heading' => 'Why AC Maintenance Matters', 'body' => "Most summer breakdowns are preventable. A short annual tune-up keeps your air conditioner cooling efficiently when you need it most.\n\nPrevent Unexpected Breakdowns — Regular tune-ups catch worn parts early, before they leave you sweating through a heatwave on the hottest day of the New Jersey summer.\n\nImprove Energy Efficiency — A clean, well-charged system cools your home using far less electricity, keeping your summer utility bills in check.\n\nExtend Equipment Lifespan — Consistent maintenance keeps your AC running longer, delaying the cost of a full replacement and protecting your warranty.\n\nBetter Air Quality — Cleaning the coils and replacing filters means cleaner, healthier air circulating through your home all season. We recommend scheduling your tune-up in early spring, before the first hot stretch."],
            ['type' => 'image', 'heading' => 'Guardian Air technician performing AC repair on an outdoor unit in New Jersey', 'image_path' => '/img/cooling-hero.webp'],
            ['type' => 'section', 'heading' => 'When to Replace Your AC', 'body' => "Deciding whether to repair or replace your air conditioner can be tough. These signs usually point to replacement as the smarter long-term investment.\n\nAge — If your AC is more than 12 to 15 years old, it's far less efficient than modern units and more likely to fail. A new high-efficiency system can noticeably lower your cooling bills.\n\nFrequent Repairs — If you're calling for AC repair every summer, the repair costs often add up to more than a reliable new system would cost.\n\nUneven Cooling — Hot spots and rooms that never cool down are a sign your system can no longer keep up with demand.\n\nRising Energy Bills — An unexplained jump in cooling costs usually means your AC is losing efficiency as it wears out.\n\nNot sure which way to go? We'll give you an honest assessment and a free replacement estimate — never a hard sell."],
            ['type' => 'section', 'heading' => 'Cooling Systems We Service', 'body' => "Our licensed technicians install, repair, and maintain every major type of home cooling system across New Jersey.\n\nCentral Air Conditioning — The most popular whole-home option, cooling every room evenly through your existing ductwork from a single outdoor unit.\n\nHeat Pumps — Energy-efficient electric systems that both cool and heat, an ideal year-round comfort solution for New Jersey homes.\n\nDuctless Mini-Splits — A flexible, efficient choice for homes without ductwork or for cooling specific rooms, additions, and converted spaces.\n\nWindow & Wall Units — A lower-cost option for individual rooms, perfect for smaller spaces or supplementing your main system.\n\nDual-Zone Systems — Independently control the temperature in different areas of your home, improving comfort while saving energy."],
            ['type' => 'section', 'heading' => 'Common AC Problems We Fix', 'body' => "Air conditioners fail in predictable ways, and our technicians diagnose and repair them every day across New Jersey.\n\nAC Blowing Warm Air — Usually a thermostat setting, low refrigerant from a leak, a dirty condenser coil, or a frozen evaporator coil.\n\nAC Won't Turn On — Often a tripped breaker, a failed capacitor or contactor, or a control-board issue.\n\nWater Leaks — Typically a clogged condensate drain line or a full drain pan, which we clear before it causes water damage or mold.\n\nFrozen Coils — Caused by restricted airflow from a dirty filter or by low refrigerant; we find and fix the root cause.\n\nStrange Noises or Odors — Rattling, buzzing, or musty smells point to loose parts, electrical faults, or mold that should be addressed quickly."],
            ['type' => 'section', 'heading' => 'Emergency AC Repair', 'body' => "When your air conditioning fails during a New Jersey heatwave, waiting isn't an option — especially for families with young children, seniors, or anyone with health concerns. Guardian Air offers fast emergency AC repair across Monmouth, Middlesex, and Ocean counties.\n\nWhen you call, you reach a real person who dispatches a licensed technician quickly, stocked to handle most repairs on the first visit. And because our pricing is flat-rate, you'll never pay extra for evenings, weekends, or holidays. Honest emergency cooling service when you need it most."],
            ['type' => 'section', 'heading' => 'Serving Monmouth, Middlesex & Ocean County', 'body' => "Guardian Air provides trusted AC repair and air conditioning service to homeowners throughout central New Jersey. Our technicians are local, which means faster response times during the summer rush and a team that knows the systems common to the area.\n\nWe proudly serve Toms River, Freehold, Brick, Old Bridge, Red Bank, and Lakewood, along with surrounding communities across all three counties. From the Ocean County shore to the neighborhoods of Middlesex and Monmouth, the same trusted technicians keep your home cool.\n\nDon't see your town listed? We almost certainly still serve it — give us a call to confirm and schedule your AC repair or tune-up today."],
            ['type' => 'faq', 'heading' => 'How much does AC repair cost in NJ?', 'body' => 'Most AC repairs in New Jersey range from $150 to $600 depending on the part — a capacitor or contactor is on the lower end, while a refrigerant recharge or compressor work is higher. We always provide a flat-rate quote before any work begins, so you know the full cost upfront with no surprises.'],
            ['type' => 'faq', 'heading' => 'Why is my AC blowing warm air?', 'body' => 'The most common causes are a thermostat set incorrectly, a clogged air filter, low refrigerant from a leak, a dirty condenser coil, or a frozen evaporator coil. A quick diagnostic pinpoints the exact issue so we can fix it fast.'],
            ['type' => 'faq', 'heading' => 'Should I repair or replace my air conditioner?', 'body' => 'If your unit is under 10 years old and the repair is minor, fixing it usually makes sense. For older systems with frequent breakdowns or an expensive repair like a compressor, replacement is often the smarter long-term investment. We give you an honest recommendation either way.'],
            ['type' => 'faq', 'heading' => 'What size air conditioner does my home need?', 'body' => 'Proper AC sizing depends on your home\'s square footage, insulation, windows, and layout — not just a rule of thumb. An undersized unit struggles in heat, while an oversized one short-cycles and wastes energy. We perform a load calculation to recommend the right size for your home.'],
            ['type' => 'faq', 'heading' => 'Do you offer emergency AC repair in Monmouth County?', 'body' => 'Yes. We provide fast emergency AC repair across Monmouth County and the surrounding areas, including Freehold, Red Bank, Middletown, and Howell. Call us and we\'ll dispatch a licensed technician as quickly as possible — at the same flat rate, day or night.'],
        ];
    }

    private function plumbing(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Plumbing Service Overview', 'body' => "Plumbing problems never happen at a convenient time. A burst pipe at 2 AM, a water heater that dies on a holiday weekend, or a slow leak that has been hiding behind your walls — our licensed plumbers show up fast and fix it right.\n\nWe handle everything from routine repairs to full repiping projects. Every job gets a clear, flat-rate quote before we start. No hourly billing, no hidden fees, and no upsells on parts you do not need."],
            ['type' => 'section', 'heading' => 'Why Plumbing Maintenance Matters', 'body' => "Staying ahead of plumbing problems protects your home and your wallet. A little preventive care goes a long way.\n\nPrevent Costly Water Damage — Catching a small drip or hidden leak early stops it from becoming a flooded basement, ruined drywall, or a mold problem that costs thousands to fix.\n\nProtect Your Water Quality — Routine checks keep pipes, water heaters, and fixtures free of buildup and corrosion, so the water reaching your taps stays clean and safe.\n\nExtend the Life of Your System — Flushing your water heater and inspecting your pipes keeps everything running longer, delaying the cost of major replacements for years."],
            ['type' => 'image', 'heading' => 'Guardian Air plumber working on pipes in a New Jersey home', 'image_path' => '/img/plumbing-hero.webp'],
            ['type' => 'section', 'heading' => 'Signs You Need A Plumber', 'body' => "Small plumbing issues rarely fix themselves. Keep an eye out for these warning signs.\n\nLow Water Pressure — A sudden drop in pressure often points to a hidden leak, a clog, or corrosion building up inside your pipes that needs attention.\n\nPersistent Drips & Leaks — A dripping faucet or a leak under the sink wastes water and signals worn seals or fittings that will only get worse over time.\n\nSlow or Backed-Up Drains — Drains that empty slowly or gurgle usually mean a clog or a deeper blockage in the line that a plunger will not fix.\n\nDiscolored or Smelly Water — Rusty, cloudy, or foul-smelling water is a sign of corroded pipes or a failing water heater that should be inspected right away.\n\nNoticing any of these? Schedule a plumbing inspection and we'll find and fix the problem fast."],
            ['type' => 'section', 'heading' => 'Plumbing Services We Offer', 'body' => "Here's a quick guide to the plumbing services our licensed team provides.\n\nLeak Detection & Repair — We pinpoint hidden leaks behind walls and under floors with no guesswork, then fix the source before it causes water damage.\n\nWater Heater Service — Repair, replacement, and installation of traditional tank and tankless water heaters for reliable hot water all year.\n\nPipe Replacement & Repiping — From a single corroded section to a full home repipe, we replace failing pipes with durable, long-lasting materials.\n\nDrain & Sewer Cleaning — Fast clearing of clogged drains and main sewer lines using professional tools that protect your pipes.\n\nEmergency Plumbing — Burst pipes, overflowing toilets, and no-water emergencies handled with same-day, around-the-clock response."],
            ['type' => 'faq', 'heading' => 'How do I know if I have a hidden water leak?', 'body' => 'Watch for an unexplained jump in your water bill, the sound of running water when everything is off, damp spots or stains on walls and ceilings, or a musty smell. We use professional leak detection to find the source without tearing up your home.'],
            ['type' => 'faq', 'heading' => 'How long does a water heater last?', 'body' => 'A traditional tank water heater typically lasts 8 to 12 years, while a tankless unit can run 20 years or more with proper maintenance. If yours is near the end of its life or needs frequent repairs, replacement is usually the smarter investment.'],
            ['type' => 'faq', 'heading' => 'Why do my drains keep clogging?', 'body' => 'Recurring clogs are usually caused by grease buildup, hair, soap scum, or tree roots in the main line. A one-time clear may not solve a deeper blockage, so we inspect the line to find and fix the real cause.'],
            ['type' => 'faq', 'heading' => 'What should I do during a plumbing emergency?', 'body' => 'Shut off the water supply right away — either the fixture valve or your main shutoff — to limit the damage, then call us. We offer same-day emergency service for burst pipes, major leaks, and overflowing fixtures.'],
            ['type' => 'faq', 'heading' => 'Can I fix a leaky faucet myself?', 'body' => 'A simple washer or cartridge swap is fine for a handy homeowner. But if the leak keeps coming back, the fixture is corroded, or you spot water under the sink, it is worth having a licensed plumber take a look before it gets worse.'],
            ['type' => 'faq', 'heading' => 'How much does plumbing repair cost?', 'body' => 'It depends on the job, but we always give you a clear, flat-rate quote before any work begins. No hourly billing, no hidden fees, and no surprise charges once the work is done.'],
            ['type' => 'faq', 'heading' => 'Is a tankless water heater worth it?', 'body' => 'For many homes, yes. Tankless units heat water on demand, never run out during long showers, take up far less space, and last longer than tank models. We can help you decide if one fits your home and budget.'],
            ['type' => 'faq', 'heading' => 'Why is my water pressure suddenly low?', 'body' => 'Low pressure can come from a hidden leak, mineral buildup in the pipes, a failing pressure regulator, or an issue with the municipal supply. A quick diagnostic visit will pinpoint the exact cause.'],
            ['type' => 'faq', 'heading' => 'Do you offer repiping for older homes?', 'body' => 'Yes. Many older New Jersey homes still have aging galvanized or polybutylene pipes that corrode and leak. We replace them with modern, long-lasting materials to restore safe, reliable water flow.'],
            ['type' => 'faq', 'heading' => 'Are your plumbers licensed and insured?', 'body' => 'Absolutely. Every Guardian Air plumber is fully licensed, insured, and bonded, so you get safe, code-compliant work backed by a guarantee on every visit.'],
        ];
    }

    private function electrical(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Electrical Service Overview', 'body' => "Electrical work is not a DIY project. Whether you need a panel upgrade to handle modern appliances, new outlets for a home office, or emergency repairs for a tripped breaker, our licensed electricians deliver safe, code-compliant work every time.\n\nWe handle residential and light commercial electrical projects of all sizes. Every job starts with a thorough inspection and a flat-rate quote. We explain what needs to be done, why it matters for your safety, and what it will cost — before we touch a single wire."],
            ['type' => 'section', 'heading' => 'Why Electrical Safety Matters', 'body' => "Your home's electrical system powers everything you rely on, and when it's neglected, the risks add up fast. Staying on top of it protects your home and your family.\n\nPrevent Electrical Fires — Faulty wiring and overloaded circuits are a leading cause of home fires. Regular inspections catch hidden hazards before they become dangerous.\n\nProtect Your Appliances — Proper wiring and surge protection shield your electronics and appliances from damaging power spikes, extending their lifespan.\n\nStay Code-Compliant — Outdated or DIY wiring can fail inspection and void insurance. Licensed work keeps your home up to current electrical code and safe for your family."],
            ['type' => 'image', 'heading' => 'Guardian Air electrician working on a residential electrical panel in New Jersey', 'image_path' => '/img/electrical.webp'],
            ['type' => 'section', 'heading' => 'Signs You Need An Electrician', 'body' => "Electrical problems rarely fix themselves. Watch for these warning signs that it's time to call a licensed pro.\n\nFrequent Tripping — Breakers that trip repeatedly or fuses that blow often signal an overloaded circuit or a wiring fault that needs professional attention.\n\nFlickering or Dimming Lights — Lights that flicker or dim when appliances turn on point to loose connections, an overloaded panel, or aging wiring.\n\nWarm Outlets or Burning Smell — Outlets or switches that feel warm, spark, or give off a burning odor are serious fire hazards. Shut off the circuit and call us right away.\n\nOutdated Panel or Wiring — Homes with a fuse box, aluminum wiring, or a panel under 100 amps often can't safely handle modern electrical demands.\n\nNoticing any of these in your home? Schedule an electrical inspection and we'll get to the root of it."],
            ['type' => 'section', 'heading' => 'Electrical Services We Offer', 'body' => "Here's a quick guide to the electrical work we install, repair, and maintain.\n\nPanel Upgrades — Modernize your electrical panel to safely handle today's appliances, EV chargers, and high-demand circuits with confidence.\n\nWiring & Rewiring — New circuits, full-home rewires, and repairs to damaged or outdated wiring, all done to current code for lasting safety.\n\nLighting & Fixtures — Recessed lighting, ceiling fans, outdoor and accent fixtures installed cleanly to brighten and elevate every room.\n\nOutlets & Switches — New outlets, GFCI installations, dimmers, and smart switches added wherever you need safe, convenient power.\n\nGenerators & EV Chargers — Standby generator hookups and Level 2 EV charger installs that keep you powered and ready for the future."],
            ['type' => 'faq', 'heading' => 'How do I know if my electrical panel needs an upgrade?', 'body' => 'If you have a fuse box, a panel rated under 100 amps, frequently tripping breakers, or you\'re adding major appliances or an EV charger, it\'s likely time for an upgrade. We can assess your panel and recommend the right capacity for your home.'],
            ['type' => 'faq', 'heading' => 'Why do my circuit breakers keep tripping?', 'body' => 'Repeated tripping usually means a circuit is overloaded, or there\'s a short circuit or ground fault. It\'s the breaker doing its job, but persistent tripping points to an underlying issue a licensed electrician should diagnose.'],
            ['type' => 'faq', 'heading' => 'Is it safe to do my own electrical work?', 'body' => 'Swapping a light bulb or resetting a tripped breaker is fine. Anything involving wiring, outlets, panels, or new circuits should be left to a licensed electrician — DIY electrical mistakes can cause fires, shocks, and failed inspections.'],
            ['type' => 'faq', 'heading' => 'What causes flickering or dimming lights?', 'body' => 'Flickering often comes from loose wiring, an overloaded circuit, a failing fixture, or a panel that can\'t keep up with demand. If it happens throughout the house, it\'s worth having the system inspected.'],
            ['type' => 'faq', 'heading' => 'Why do my outlets feel warm or spark?', 'body' => 'A warm outlet, sparking, or a burning smell signals loose connections, overloading, or damaged wiring, all serious fire risks. Stop using the outlet, turn off the circuit, and call us for same-day service.'],
            ['type' => 'faq', 'heading' => 'What is a GFCI outlet and where do I need them?', 'body' => 'A GFCI (Ground Fault Circuit Interrupter) outlet shuts off power instantly if it detects a fault, preventing shocks. Code requires them in kitchens, bathrooms, garages, basements, and outdoor areas.'],
            ['type' => 'faq', 'heading' => 'Can you install an EV charger at my home?', 'body' => 'Yes. We install Level 2 EV chargers, including any panel upgrades or dedicated circuits needed to support them safely. We\'ll evaluate your panel capacity and recommend the best setup for your vehicle.'],
            ['type' => 'faq', 'heading' => 'Do I need a permit for electrical work?', 'body' => 'Most electrical work — panel upgrades, new circuits, and rewiring — requires a permit and inspection. As licensed electricians, we handle the permitting process and ensure every job passes inspection.'],
            ['type' => 'faq', 'heading' => "How often should I have my home's wiring inspected?", 'body' => "We recommend an inspection every few years for newer homes, and sooner for homes over 25 years old or any home you've just purchased. Aluminum wiring and older panels should be checked promptly."],
            ['type' => 'faq', 'heading' => 'What should I do during an electrical emergency?', 'body' => 'If you smell burning, see sparks, or have exposed wiring, shut off power at the breaker if it\'s safe to do so and keep away from the area. Then call us — we offer same-day emergency electrical service.'],
        ];
    }

    private function airQuality(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Indoor Air Quality Overview', 'body' => "The air inside your home can be up to five times more polluted than the air outside. Dust, pollen, pet dander, mold spores, and volatile organic compounds all circulate through your HVAC system — and into your lungs. We help you take control.\n\nOur team assesses your home's air quality and recommends the right mix of filtration, humidity control, and purification. From whole-home air purifiers to duct cleaning and UV germicidal lights, we have solutions for every budget and concern."],
            ['type' => 'section', 'heading' => 'Why Indoor Air Quality Matters', 'body' => "The air you breathe at home directly affects your health and comfort. Investing in better indoor air quality pays off every single day.\n\nProtect Your Health — Indoor air can be up to five times more polluted than outdoor air. Cleaner air reduces allergens, irritants, and airborne contaminants that aggravate asthma and allergies.\n\nBreathe Easier Every Day — Balanced humidity and proper filtration help everyone in your home sleep better, breathe easier, and feel more comfortable year-round.\n\nProtect Your Home & HVAC — Controlling dust, moisture, and contaminants keeps your HVAC system running efficiently and helps prevent mold growth and damage to your home."],
            ['type' => 'image', 'heading' => 'Guardian Air technician installing an air purification system in a New Jersey home', 'image_path' => '/img/air-quality-hero.webp'],
            ['type' => 'section', 'heading' => 'Signs Of Poor Air Quality', 'body' => "Poor indoor air quality isn't always obvious. Watch for these common warning signs.\n\nPersistent Dust — If dust resettles on surfaces almost as soon as you clean, your air is likely full of fine particles your filtration system is missing.\n\nAllergy & Respiratory Symptoms — Frequent sneezing, congestion, headaches, or irritated eyes indoors often point to high levels of pollen, dander, or other airborne irritants.\n\nMusty or Stale Odors — Lingering smells that won't go away can signal mold, excess moisture, or stagnant air that needs better ventilation and purification.\n\nHumidity Problems — Condensation on windows, clammy air, or overly dry air that causes static and cracked skin all indicate your home needs humidity control.\n\nNoticing any of these in your home? Schedule an air quality assessment and we'll recommend the right solution."],
            ['type' => 'section', 'heading' => 'Air Quality Solutions We Offer', 'body' => "Here's a quick guide to the indoor air quality solutions we install and service.\n\nAir Purifiers — Whole-home systems that capture allergens, dust, smoke, and microscopic particles before they circulate through your living space.\n\nHumidifiers — Add balanced moisture to dry winter air, easing dry skin, static, and respiratory discomfort while protecting woodwork and furniture.\n\nDehumidifiers — Remove excess moisture to prevent mold, mildew, and that heavy, clammy feeling during humid New Jersey summers.\n\nUV Germicidal Lights — Installed in your HVAC system to neutralize mold, bacteria, and viruses as air passes through the coil and ductwork.\n\nDuct Cleaning — Clears built-up dust, debris, and allergens from your ductwork so the air delivered to every room is as clean as possible."],
            ['type' => 'faq', 'heading' => 'How do I know if my home has poor indoor air quality?', 'body' => 'Common warning signs include persistent dust, lingering musty odors, increased allergy or respiratory symptoms indoors, and humidity problems like condensation or overly dry air. An air quality test gives you a clear picture.'],
            ['type' => 'faq', 'heading' => 'What causes poor indoor air quality?', 'body' => 'Dust, pollen, pet dander, mold spores, volatile organic compounds (VOCs), and excess or insufficient humidity all reduce air quality. Many of these contaminants circulate through your HVAC system and into the air you breathe.'],
            ['type' => 'faq', 'heading' => 'How often should I change my air filter?', 'body' => 'Most standard filters should be replaced every one to three months, depending on the filter type, whether you have pets, and how often the system runs. High-efficiency and allergy-rated filters may have different intervals.'],
            ['type' => 'faq', 'heading' => 'Do air purifiers really work?', 'body' => 'Yes. A properly sized whole-home air purifier captures airborne particles like dust, pollen, smoke, and dander before they recirculate, noticeably reducing allergens and improving the air throughout your home.'],
            ['type' => 'faq', 'heading' => 'What is the ideal indoor humidity level?', 'body' => 'Most homes are most comfortable between 30% and 50% relative humidity. Too low causes dry skin and static; too high encourages mold and dust mites. Humidifiers and dehumidifiers help you hit the right balance.'],
            ['type' => 'faq', 'heading' => 'How does a UV germicidal light improve air quality?', 'body' => 'UV lights installed in your HVAC system neutralize mold, bacteria, and viruses as air passes over the coil and through the ductwork, helping keep your system clean and the circulating air healthier.'],
            ['type' => 'faq', 'heading' => 'Is duct cleaning worth it?', 'body' => 'Duct cleaning is worthwhile when there\'s visible mold, excessive dust, debris, or signs of pests in the ductwork. Clean ducts help your system run efficiently and stop recirculating contaminants through your home.'],
            ['type' => 'faq', 'heading' => 'Can poor air quality affect my allergies or asthma?', 'body' => 'Absolutely. Airborne allergens such as dust, pollen, pet dander, and mold spores are common asthma and allergy triggers. Improving filtration and controlling humidity often reduces symptoms significantly.'],
            ['type' => 'faq', 'heading' => 'What is the difference between an air purifier and an air filter?', 'body' => 'A filter traps particles as air passes through it, while a purifier actively treats the air using advanced filtration and technologies like UV light or ionization to remove or neutralize a wider range of contaminants.'],
            ['type' => 'faq', 'heading' => 'Do you offer indoor air quality testing?', 'body' => 'Yes. We assess your home, measure key air quality factors, and recommend the right mix of filtration, humidity control, and purification tailored to your concerns and budget.'],
        ];
    }

    private function drains(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Drain Service Overview', 'body' => "A slow drain or backed-up sewer line is more than an inconvenience — it can damage your home and create serious health hazards. Our drain specialists use professional-grade equipment to identify the root cause and clear it completely, not just punch a temporary hole through the clog.\n\nWe start with a camera inspection when needed, so you see exactly what is causing the problem. Then we use the right tool for the job, from motorized drain snakes to high-pressure hydro jetting that scrubs your pipes clean. We leave your home as clean as we found it."],
            ['type' => 'section', 'heading' => 'Why Drain Maintenance Matters', 'body' => "Regular drain maintenance is crucial to keep your plumbing flowing freely and avoid costly emergencies. A little upkeep protects your home and your wallet.\n\nPrevent Costly Backups — Routine cleaning clears buildup before it becomes a full blockage, avoiding messy, expensive sewage backups inside your home.\n\nProtect Your Pipes — Grease, hair, and mineral scale slowly corrode and clog your lines. Regular maintenance keeps pipes flowing freely and extends their lifespan.\n\nStop Odors & Health Hazards — Standing water and trapped debris breed bacteria and foul smells. Keeping drains clear protects your home and your family from health risks."],
            ['type' => 'image', 'heading' => 'Guardian Air drain technician clearing a clogged drain in a New Jersey home', 'image_path' => '/img/drains-hero.webp'],
            ['type' => 'section', 'heading' => 'Signs Of A Drain Problem', 'body' => "Catching a drain issue early saves you from a messy backup. Watch for these warning signs.\n\nSlow Drainage — Water that pools and takes its time emptying out of a sink, tub, or shower is the earliest sign of a developing clog.\n\nGurgling Sounds — Bubbling or gurgling noises from your drains mean air is trapped behind a blockage struggling to push through the line.\n\nFoul Odors — Persistent sewage or rotten smells usually point to trapped debris, a venting issue, or a partial blockage deep in the line.\n\nFrequent Clogs — If you are plunging the same drain over and over, the real problem is likely further down the line and needs professional clearing.\n\nNoticing one of these warning signs? Schedule a drain inspection and we'll clear it before it becomes an emergency."],
            ['type' => 'section', 'heading' => 'Drain Services We Offer', 'body' => "Here's a quick guide to the drain services our licensed technicians provide.\n\nDrain Cleaning — Motorized snaking and augering that breaks up and removes clogs in sinks, tubs, showers, and floor drains quickly.\n\nHydro Jetting — High-pressure water scours the inside of your pipes, blasting away grease, scale, and roots for a like-new, fully clear line.\n\nCamera Inspections — A waterproof camera travels through your line so you see the exact cause and location of the problem before any work begins.\n\nSewer Line Repair — From spot repairs to full line replacement, we fix cracked, collapsed, and root-invaded sewer lines that cause repeat backups.\n\nEmergency Service — When a main line backs up or a drain floods, our team responds the same day to clear the blockage and protect your home."],
            ['type' => 'faq', 'heading' => 'How often should I have my drains cleaned?', 'body' => 'For most homes, a professional drain cleaning every one to two years keeps lines clear and prevents backups. Homes with older pipes, large families, or a history of clogs may benefit from yearly service.'],
            ['type' => 'faq', 'heading' => 'What causes a clogged drain?', 'body' => 'The usual culprits are grease and food in kitchen drains, hair and soap scum in bathrooms, mineral buildup, foreign objects, and tree roots invading the main sewer line.'],
            ['type' => 'faq', 'heading' => 'Are chemical drain cleaners safe to use?', 'body' => 'We generally advise against them. Store-bought chemicals can corrode your pipes, are harmful to handle, and often only punch a small hole through the clog instead of clearing it completely.'],
            ['type' => 'faq', 'heading' => 'What is hydro jetting and do I need it?', 'body' => 'Hydro jetting uses high-pressure water to scrub the inside of your pipes clean, removing grease, scale, and roots. It is ideal for stubborn or recurring clogs and badly built-up lines.'],
            ['type' => 'faq', 'heading' => 'How do I know if the clog is in my main sewer line?', 'body' => 'Warning signs include multiple drains backing up at once, gurgling toilets when you run a sink, water pooling around floor drains, or sewage odors. These point to a main line blockage that needs professional clearing.'],
            ['type' => 'faq', 'heading' => 'Can tree roots really damage my sewer line?', 'body' => 'Yes. Roots seek out moisture and can grow into tiny cracks or joints in your sewer line, eventually causing major blockages or breaks. A camera inspection confirms root intrusion so we can clear and repair it.'],
            ['type' => 'faq', 'heading' => 'Why does my drain smell bad even after cleaning?', 'body' => 'Lingering odors are often caused by trapped debris, a dry P-trap, or a venting problem rather than a clog. We can diagnose the source and eliminate the smell at its origin.'],
            ['type' => 'faq', 'heading' => 'Do you use a camera to inspect drains?', 'body' => 'When needed, yes. A drain camera lets us see the exact cause and location of a problem inside your pipes, so we recommend the right fix instead of guessing.'],
            ['type' => 'faq', 'heading' => 'Will drain cleaning make a mess in my home?', 'body' => 'No. Our technicians lay down protection, work cleanly, and leave your home as tidy as we found it — no mess left behind is part of every job.'],
            ['type' => 'faq', 'heading' => 'Do you offer emergency drain service?', 'body' => 'Yes. A backed-up main line or flooding drain cannot wait. We offer same-day and emergency response to clear the blockage and prevent water damage to your home.'],
        ];
    }

    private function commercial(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Commercial Services Overview', 'body' => "When your commercial HVAC system fails on a 95-degree day or a burst pipe floods your retail space, every minute of downtime costs money. We understand that business owners need fast, reliable service that minimizes disruption and gets operations back to normal.\n\nOur commercial team handles rooftop units, boilers, chillers, commercial plumbing, and electrical work for offices, restaurants, retail spaces, and multi-family buildings. We offer preventative maintenance programs to catch problems before they become emergencies, and 24/7 response when they do."],
            ['type' => 'section', 'heading' => 'Why Preventive Maintenance Matters', 'body' => "For a business, an unexpected equipment failure means lost revenue and unhappy customers. A scheduled maintenance program protects your operation and your bottom line.\n\nReduce Costly Downtime — Scheduled inspections catch worn parts and small failures early, before they shut down your business during peak hours and cost you revenue.\n\nLower Operating Costs — Well-maintained commercial systems run more efficiently, cutting your energy bills and keeping monthly operating expenses predictable.\n\nProtect Your Equipment Investment — Routine service extends the life of rooftop units, boilers, and chillers, delaying expensive replacements and keeping warranties valid."],
            ['type' => 'image', 'heading' => 'Guardian Air commercial technician servicing a rooftop HVAC unit in New Jersey', 'image_path' => '/img/commercial-hero.webp'],
            ['type' => 'section', 'heading' => 'Industries We Serve', 'body' => "We tailor our commercial HVAC, plumbing, and electrical service to the unique demands of each type of facility we work with.\n\nOffices & Professional Buildings — Consistent comfort for tenants and staff, with discreet scheduling that keeps your workday running without interruption.\n\nRestaurants & Food Service — Make-up air, refrigeration, and plumbing service that meets health-code standards and keeps your kitchen open for business.\n\nRetail & Shopping Centers — Reliable heating and cooling that keeps customers comfortable and your storefront inviting throughout every season.\n\nMulti-Family & Property Management — Building-wide HVAC and plumbing maintenance for apartments and condos, with fast response for tenant emergencies.\n\nDon't see your industry listed? Tell us about your facility and we'll build a service plan that fits."],
            ['type' => 'section', 'heading' => 'Commercial Services We Offer', 'body' => "Here's a quick guide to the commercial systems we install, service, and maintain.\n\nRooftop Units (RTUs) — Installation, repair, and tune-ups for packaged rooftop systems that heat and cool commercial spaces efficiently.\n\nCommercial Boilers — Service and replacement for hydronic and steam boilers that deliver reliable heat to larger facilities.\n\nChillers & Cooling — Maintenance and repair for chiller systems that keep temperature-sensitive operations running smoothly.\n\nCommercial Plumbing — Water heaters, drain lines, fixtures, and backflow service sized for the demands of a busy commercial property.\n\nPreventative Maintenance Plans — Custom maintenance agreements with scheduled visits, priority response, and documented service for your equipment."],
            ['type' => 'faq', 'heading' => 'Do you offer commercial maintenance contracts?', 'body' => 'Yes. We build custom preventative maintenance plans with scheduled visits, priority response, and detailed service records — tailored to your equipment and budget so problems get caught before they become emergencies.'],
            ['type' => 'faq', 'heading' => 'How quickly can you respond to a commercial emergency?', 'body' => 'Our team is available 24/7 for commercial HVAC and plumbing emergencies. Maintenance-plan clients receive priority response, and in most cases we can have a technician on-site the same day.'],
            ['type' => 'faq', 'heading' => 'Can you service rooftop HVAC units?', 'body' => 'Absolutely. We install, repair, and tune up packaged rooftop units (RTUs) of all sizes, including filter changes, belt and motor service, refrigerant checks, and full system diagnostics.'],
            ['type' => 'faq', 'heading' => 'Do you work on commercial boilers and chillers?', 'body' => 'Yes. We service hydronic and steam boilers as well as chiller systems — handling inspections, repairs, efficiency tune-ups, and replacements to keep larger facilities heated and cooled reliably.'],
            ['type' => 'faq', 'heading' => 'Will the work disrupt my business operations?', 'body' => 'We schedule around your hours whenever possible, including early mornings, evenings, and weekends, to minimize downtime. Our goal is to keep your business running while we keep your systems running.'],
            ['type' => 'faq', 'heading' => 'Are you licensed and insured for commercial work?', 'body' => 'Yes. Every Guardian Air technician is fully licensed, insured, and trained in commercial HVAC, plumbing, and electrical work, so your project is code-compliant and properly documented.'],
            ['type' => 'faq', 'heading' => 'Do you handle commercial plumbing?', 'body' => 'We do. From commercial water heaters and drain lines to fixtures and backflow testing, we handle plumbing sized for the higher demands of offices, restaurants, retail, and multi-family buildings.'],
            ['type' => 'faq', 'heading' => 'How often should commercial HVAC be serviced?', 'body' => 'Most commercial systems should be serviced at least twice a year — before the heating season and before the cooling season. High-use equipment like restaurant make-up air may need more frequent visits.'],
            ['type' => 'faq', 'heading' => 'Can you provide service for multiple locations?', 'body' => 'Yes. We work with property managers and multi-location businesses to standardize maintenance and reporting across all of your buildings, with a single point of contact for scheduling and billing.'],
            ['type' => 'faq', 'heading' => 'What types of businesses do you work with?', 'body' => 'We serve offices, restaurants, retail and shopping centers, and multi-family and managed properties across Monmouth, Middlesex, and Ocean counties, and we are happy to assess any commercial space.'],
        ];
    }
}
