<?php

namespace Database\Seeders;

use App\Models\ContentBlock;
use Illuminate\Database\Seeder;

class ContentBlockSeeder extends Seeder
{
    /**
     * Seed the service pages' article content as editable blocks.
     *
     * Non-destructive: a page is only populated when it currently has NO
     * blocks. Pages the admin has already added to or edited are left
     * untouched, so running this seeder never wipes admin changes. This
     * makes it safe to run on every deploy to fill in any empty pages.
     *
     * To intentionally reset a page back to these defaults, delete its
     * blocks in the admin panel (or the DB) first, then re-run the seeder.
     */
    /**
     * The full default content for every page, keyed by page slug.
     * Exposed so the `content:reset` command can re-apply defaults.
     */
    public function data(): array
    {
        return [
            'heating' => $this->heating(),
            'cooling' => $this->cooling(),
            'plumbing' => $this->plumbing(),
            'electrical' => $this->electrical(),
            'indoor-air-quality' => $this->airQuality(),
            'drains' => $this->drains(),
            'commercial' => $this->commercial(),
        ];
    }

    public function run(): void
    {
        $pages = $this->data();

        foreach ($pages as $page => $blocks) {
            // Skip any page that already has content — preserves admin edits.
            if (ContentBlock::where('page', $page)->exists()) {
                continue;
            }

            foreach ($blocks as $i => $block) {
                ContentBlock::create(array_merge($block, ['page' => $page, 'position' => $i]));
            }
        }
    }

    private function heating(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Furnace Repair in NJ', 'body' => "<p>When your furnace quits on a freezing January night, you need furnace repair in NJ that shows up fast and gets it right the first time. Guardian Air is a licensed and insured heating company serving homeowners across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a> with same-day furnace repair, honest diagnostics, and upfront, flat-rate pricing — no overtime surprises and no pressure.</p><p>Our technicians repair every make and model of gas, electric, and oil furnace, and we also service <a href='/heating/boiler-repair'>boilers</a> and <a href='/heating/heat-pump'>heat pumps</a>. From a furnace that blows cold air to a unit that won't ignite at all, we pinpoint the real problem and fix it on the spot whenever possible, with common parts stocked on every truck.</p><p>Every furnace repair starts with a clear explanation of what's wrong and what it will cost. When a fix no longer makes sense, we'll walk you through <a href='/heating/furnace-replacement'>furnace replacement</a> — or you can <a href='/contact'>schedule service</a> online anytime.</p>"],
            ['type' => 'section', 'heading' => 'Why Furnace Maintenance Matters', 'body' => "<p>Most no-heat emergencies are preventable. A short annual <a href='/heating/furnace-tune-up'>furnace tune-up</a> protects your comfort, your safety, and your wallet all winter long.</p><p><strong>Prevent Unexpected Breakdowns</strong> — Regular inspections catch worn parts early, before they turn into a no-heat <a href='/contact'>emergency</a> on the coldest night of the year.</p><p><strong>Improve Energy Efficiency</strong> — A clean, well-tuned furnace burns less fuel to heat your home; for year-round savings, ask about an efficient <a href='/heating/heat-pump'>heat pump</a>.</p><p><strong>Extend Equipment Lifespan</strong> — Consistent maintenance keeps your system running longer, delaying the cost of a full <a href='/heating/furnace-replacement'>furnace replacement</a> and protecting your warranty.</p><p><strong>Protect Your Family's Safety</strong> — A maintenance visit includes a carbon monoxide and heat-exchanger check. <a href='/contact'>Schedule your tune-up</a> in early fall, before the first cold snap.</p>"],
            ['type' => 'image', 'heading' => 'Guardian Air technician performing furnace repair in a New Jersey home', 'image_path' => '/img/heating-hero.webp'],
            ['type' => 'section', 'heading' => 'When to Replace Your Furnace', 'body' => "<p>Deciding whether to repair or replace your furnace can be tough. These signs usually mean <a href='/heating/furnace-replacement'>furnace replacement</a> is the smarter long-term investment.</p><p><strong>Age</strong> — If your furnace is more than 15 years old, it's far less efficient than modern units. Newer <a href='/heating/furnace-replacement'>high-efficiency systems</a> can noticeably cut your heating bills.</p><p><strong>Frequent Repairs</strong> — If you're calling for repairs every season, a new system often costs less over time, and regular <a href='/heating/furnace-tune-up'>maintenance</a> helps prevent breakdowns.</p><p><strong>Uneven or Weak Heat</strong> — Cold spots and rooms that never warm up are a sign your furnace can't keep up. A <a href='/heating/heat-pump'>heat pump</a> is one efficient alternative we install.</p><p><strong>Rising Energy Bills</strong> — An unexplained jump in heating costs usually means lost efficiency. We serve homeowners across <a href='/service-areas'>central New Jersey</a> with honest assessments.</p><p>Not sure which way to go? <a href='/contact'>Contact us</a> for a free replacement estimate — never a hard sell.</p>"],
            ['type' => 'section', 'heading' => 'Heating Systems We Service', 'body' => "<p>Our licensed technicians install, repair, and maintain every major type of home heating system across <a href='/service-areas'>New Jersey</a>.</p><p><strong>Gas Furnaces</strong> — The most common and cost-effective option, burning natural gas for fast, powerful, whole-home heat.</p><p><strong>Oil Furnaces</strong> — Common in older New Jersey homes, delivering strong, reliable heat output; we service and tune oil systems of every age.</p><p><strong>Electric Furnaces</strong> — A great fit for homes without a gas line, using electric heating elements for clean, simple heat.</p><p><strong><a href='/heating/heat-pump'>Heat Pumps</a></strong> — Energy-efficient electric systems that both heat and cool, ideal for year-round comfort and lower operating costs.</p><p><strong><a href='/heating/boiler-repair'>Boilers</a></strong> — Steady radiant warmth through hot water; we repair leaks, pressure problems, and no-heat issues. Considering an upgrade? Explore our <a href='/heating/furnace-replacement'>furnace replacement</a> options or book a furnace tune-up.</p>"],
            ['type' => 'section', 'heading' => 'No-Heat Emergency Service 24/7', 'body' => "<p>A heating failure in the middle of a New Jersey winter can't wait until morning. That's why Guardian Air offers 24/7 no-heat emergency furnace repair across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a>.</p><p>When you call, you reach a real person who dispatches a licensed technician fast — stocked to handle most repairs on the first visit, whether it's your furnace, a <a href='/heating/boiler-repair'>boiler</a>, or a failed safety switch.</p><p>And because our pricing is flat-rate, you'll never pay extra for nights, weekends, or holidays. <a href='/contact'>Schedule emergency service</a> when you need it most.</p>"],
            ['type' => 'section', 'heading' => 'Serving Monmouth, Middlesex & Ocean County', 'body' => "<p>Guardian Air provides trusted furnace repair and heating service to homeowners throughout <a href='/service-areas'>central New Jersey</a>. Our technicians are local, which means faster response times and a team that knows the older oil systems and newer high-efficiency furnaces common to the area.</p><p>We proudly serve <a href='/heating/toms-river'>Toms River</a>, <a href='/heating/freehold'>Freehold</a>, Brick, Old Bridge, Red Bank, and Lakewood, along with surrounding communities across all three counties.</p><p>Don't see your town listed? We almost certainly still serve it — <a href='/contact'>give us a call</a> to confirm and schedule your furnace repair or tune-up today.</p>"],
            ['type' => 'faq', 'heading' => 'How much does furnace repair cost in NJ?', 'body' => 'Most furnace repairs in New Jersey fall between $150 and $750 depending on the failed part — an igniter or flame sensor is on the lower end, while a blower motor or control board is higher. We always provide a flat-rate quote before any work begins, so you know the full cost upfront with no surprises.'],
            ['type' => 'faq', 'heading' => 'When should I replace my furnace instead of repairing it?', 'body' => 'Replacement usually makes sense when your furnace is over 15 years old, needs frequent or expensive repairs, heats unevenly, or is driving up your energy bills. If a single repair is minor and the system is otherwise healthy, fixing it is the better value. We give you an honest recommendation either way.'],
            ['type' => 'faq', 'heading' => 'Why does my furnace keep shutting off?', 'body' => 'Short-cycling is most often caused by a dirty air filter restricting airflow, a malfunctioning thermostat, a clogged flue, or an overheating safety switch doing its job. A quick diagnostic visit pinpoints the exact cause and prevents further wear on the system.'],
            ['type' => 'faq', 'heading' => 'Should I choose an oil or gas furnace?', 'body' => 'Gas furnaces are typically cheaper to run and lower-maintenance where a natural gas line is available, which is why most New Jersey homeowners choose them. Oil furnaces remain a strong option for homes without gas service and can deliver very high heat output. We help you compare based on your home and local fuel costs.'],
            ['type' => 'faq', 'heading' => 'How long does a furnace installation take?', 'body' => 'A standard furnace replacement is usually completed in a single day — typically four to eight hours. More involved jobs, such as switching fuel types or modifying ductwork, may take longer. We give you a clear timeline with your free estimate.'],
            ['type' => 'faq', 'heading' => 'What areas do you serve for furnace repair?', 'body' => 'We provide furnace repair and heating service across Monmouth, Middlesex, and Ocean counties, including Toms River, Freehold, Brick, Old Bridge, Red Bank, Lakewood, and the surrounding towns. Call us to confirm service to your specific address.'],
        ];
    }

    private function cooling(): array
    {
        return [
            ['type' => 'section', 'heading' => 'AC Repair in NJ', 'body' => "<p>When your air conditioner blows warm air in the middle of a July heatwave, you need AC repair in NJ that responds fast and fixes it right. Guardian Air is a licensed and insured cooling company serving homeowners across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a> with same-day repair, honest diagnostics, and upfront, flat-rate pricing.</p><p>We repair every major brand of central air, <a href='/heating/heat-pump'>heat pump</a>, and <a href='/cooling/ductless-mini-split'>ductless system</a>. Whether your AC won't turn on, short-cycles, or can't keep up, we pinpoint the real cause and fix it on the spot whenever possible, with common parts stocked on every truck.</p><p>Every repair begins with a clear explanation and a flat-rate quote — see typical pricing in our <a href='/cost-guides/ac-repair-cost'>AC repair cost guide</a>. It's cooling service the way it should be: fast, fair, and backed by a local team your neighbors trust.</p><p>Cooling equipment has changed fast — R-410A and newer refrigerants, variable-speed compressors, communicating thermostats — and our continuing-education program keeps every technician current. Whatever vintage your system is, the diagnosis starts from experience, not guesswork.</p>"],
            ['type' => 'section', 'heading' => 'Why AC Maintenance Matters', 'body' => "<p>Most summer breakdowns are preventable. A short annual <a href='/cooling/ac-tune-up'>AC tune-up</a> keeps your air conditioner cooling efficiently when you need it most.</p><p><strong>Prevent Unexpected Breakdowns</strong> — Regular tune-ups catch worn parts early, before they leave you needing <a href='/contact'>emergency service</a> on the hottest day of the summer.</p><p><strong>Improve Energy Efficiency</strong> — A clean, well-charged system cools using far less electricity; for year-round savings, consider an efficient <a href='/heating/heat-pump'>heat pump</a>.</p><p><strong>Extend Equipment Lifespan</strong> — Consistent maintenance delays the cost of a full <a href='/cooling/ac-installation'>AC replacement</a> and protects your warranty.</p><p><strong>Better Air Quality</strong> — Cleaning coils and replacing filters means cleaner air; pair it with <a href='/indoor-air-quality'>indoor air quality</a> solutions for the whole home.</p>"],
            ['type' => 'image', 'heading' => 'Guardian Air technician performing AC repair on an outdoor unit in New Jersey', 'image_path' => '/img/cooling-hero.webp'],
            ['type' => 'section', 'heading' => 'When to Replace Your AC', 'body' => "<p>Deciding whether to repair or replace your air conditioner can be tough. These signs usually point to <a href='/cooling/ac-installation'>replacement</a> as the smarter long-term investment.</p><p><strong>Age</strong> — If your AC is more than 12 to 15 years old, a new <a href='/cooling/ac-installation'>high-efficiency system</a> can noticeably lower your cooling bills.</p><p><strong>Frequent Repairs</strong> — If you're calling every summer, the repair costs (see our <a href='/cost-guides/ac-repair-cost'>cost guide</a>) often add up to more than a reliable new system.</p><p><strong>Uneven Cooling</strong> — Hot spots and rooms that never cool down may call for zoned comfort like a <a href='/cooling/ductless-mini-split'>ductless mini-split</a>.</p><p><strong>Rising Energy Bills</strong> — A jump in cooling costs usually means lost efficiency; our local techs across <a href='/service-areas'>central NJ</a> give honest assessments.</p><p>Torn between one more repair and an upgrade? <a href='/contact'>Request a free replacement estimate</a> and we'll lay out both numbers side by side.</p>"],
            ['type' => 'section', 'heading' => 'Cooling Systems We Service', 'body' => "<p>From whole-home central air to single-room ductless zones, here are the cooling systems we work on every day across <a href='/service-areas'>New Jersey</a>.</p><p><strong>Central Air Conditioning</strong> — The most popular whole-home option; we handle repair and <a href='/cooling/ac-installation'>installation</a> through your existing ductwork.</p><p><strong>Heat Pumps</strong> — Energy-efficient systems that both cool and heat; learn more on our <a href='/heating/heat-pump'>heat pump</a> page.</p><p><strong>Ductless Mini-Splits</strong> — A flexible choice for homes without ductwork or for specific rooms — see <a href='/cooling/ductless-mini-split'>ductless mini-splits</a>.</p><p><strong>Window & Wall Units</strong> — A lower-cost option for individual rooms, perfect for supplementing your <a href='/cooling/ac-installation'>main system</a>.</p><p><strong>Dual-Zone Systems</strong> — Independently control different areas of your home; keep them efficient with a yearly <a href='/cooling/ac-tune-up'>tune-up</a>.</p>"],
            ['type' => 'section', 'heading' => 'Common AC Problems We Fix', 'body' => "<p>Air conditioners fail in predictable ways, and our technicians diagnose and repair them every day across <a href='/service-areas'>New Jersey</a>.</p><p><strong>AC Blowing Warm Air</strong> — Usually a thermostat setting, low refrigerant, or a dirty coil; see costs in our <a href='/cost-guides/ac-repair-cost'>AC repair cost guide</a>.</p><p><strong>AC Won't Turn On</strong> — Often a tripped breaker, a failed capacitor or contactor, or a control board — <a href='/contact'>schedule a diagnostic</a>.</p><p><strong>Water Leaks</strong> — Typically a clogged condensate line or full drain pan; regular <a href='/cooling/ac-tune-up'>maintenance</a> prevents it.</p><p><strong>Frozen Coils</strong> — Caused by restricted airflow or low refrigerant; a <a href='/cooling/ac-tune-up'>tune-up</a> finds the root cause.</p><p><strong>Strange Noises or Odors</strong> — Musty smells can signal mold — pair repair with <a href='/indoor-air-quality'>indoor air quality</a> service.</p><p><strong>Rising Indoor Humidity</strong> — A system that cools but no longer dries the air may be oversized or losing capacity; we measure humidity along with temperature on every diagnostic visit.</p>"],
            ['type' => 'section', 'heading' => 'Emergency AC Repair', 'body' => "<p>When your air conditioning fails during a New Jersey heatwave, waiting isn't an option — especially for families with young children or seniors. Guardian Air offers fast emergency AC repair across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a>.</p><p>When you call, you reach a real person who dispatches a licensed technician quickly, stocked to handle most repairs on the first visit — and our flat-rate pricing never adds overtime fees. <a href='/contact'>Schedule emergency service</a> when you need it most.</p><p>Heat is more than a comfort problem: indoor temperatures above the mid-80s are genuinely risky for infants, seniors, and anyone on certain medications. If a cooling outage puts someone vulnerable at risk, tell us when you call — those visits move to the top of the board.</p>"],
            ['type' => 'section', 'heading' => 'Serving Monmouth, Middlesex & Ocean County', 'body' => "<p>Guardian Air provides trusted AC repair and air conditioning service to homeowners throughout central New Jersey. Our technicians are local, which means faster response times during the summer rush and a team that knows the systems common to the area.</p><p>Summer service calls take us everywhere from shore towns like <a href='/cooling/toms-river'>Toms River</a> and Brick to inland <a href='/cooling/old-bridge'>Old Bridge</a> and Edison — and most of the towns in between.</p><p>Need more than cooling? We also offer <a href='/heating'>heating</a>, <a href='/plumbing'>plumbing</a>, and indoor air quality service. If your town isn't named here, odds are we still cover it — one quick call confirms it and gets your AC repair or tune-up on the books.</p>"],
            ['type' => 'faq', 'heading' => 'How much does AC repair cost in NJ?', 'body' => 'Most AC repairs in New Jersey range from $150 to $600 depending on the part — a capacitor or contactor is on the lower end, while a refrigerant recharge or compressor work is higher. We always provide a flat-rate quote before any work begins, so you know the full cost upfront with no surprises.'],
            ['type' => 'faq', 'heading' => 'Why is my AC blowing warm air?', 'body' => 'The most common causes are a thermostat set incorrectly, a clogged air filter, low refrigerant from a leak, a dirty condenser coil, or a frozen evaporator coil. A quick diagnostic pinpoints the exact issue so we can fix it fast.'],
            ['type' => 'faq', 'heading' => 'Should I repair or replace my air conditioner?', 'body' => 'If your unit is under 10 years old and the repair is minor, fixing it usually makes sense. For older systems with frequent breakdowns or an expensive repair like a compressor, replacement is often the smarter long-term investment. We give you an honest recommendation either way.'],
            ['type' => 'faq', 'heading' => 'What size air conditioner does my home need?', 'body' => 'Proper AC sizing depends on your home\'s square footage, insulation, windows, and layout — not just a rule of thumb. An undersized unit struggles in heat, while an oversized one short-cycles and wastes energy. We perform a load calculation to recommend the right size for your home.'],
            ['type' => 'faq', 'heading' => 'Do you offer emergency AC repair in Monmouth County?', 'body' => 'Absolutely. During heatwaves we prioritize households with seniors, young children, and medical needs. Our Monmouth County techs cover Freehold, Red Bank, Middletown, Howell, and beyond — with no after-hours premium.'],
        ];
    }

    private function plumbing(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Licensed Plumber Services in NJ', 'body' => "<p>Looking for a licensed plumber in NJ you can count on? Guardian Air is a fully licensed and insured plumbing company serving homeowners across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a>. From a dripping faucet to a burst pipe at 2 AM, our plumbers show up fast and fix it right.</p><p>We handle the full range of residential plumbing: <a href='/plumbing/leak-detection'>leak detection</a>, <a href='/plumbing/water-heater'>water heater</a> repair and replacement, pipe repair and repiping, drain and sewer cleaning, and around-the-clock emergency service. No hourly billing and no hidden fees.</p><p>Every one of our plumbers is licensed, insured, and bonded — and wondering about pricing? Our <a href='/cost-guides/plumber-cost'>plumber cost guide</a> shows honest, flat-rate ranges before any work begins.</p><p>Licensing matters more in plumbing than almost any trade: gas lines, potable water, and drainage all carry real safety stakes, and New Jersey requires a master plumber's license for good reason. Every Guardian Air plumber works under that license, carries liability coverage, and pulls permits when the job calls for them — so the work passes inspection and protects your home's paper trail at resale.</p>"],
            ['type' => 'section', 'heading' => 'Emergency Plumber 24/7', 'body' => "<p>Plumbing emergencies never wait for business hours. A burst pipe or overflowing toilet can cause serious damage in minutes — which is why Guardian Air offers <a href='/plumbing/emergency-plumber'>24/7 emergency plumber</a> service across all three counties.</p><p>When you call, you reach a real person who dispatches a licensed plumber fast, stocked to handle most repairs on the first visit. We serve <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a> and help you shut off the water to limit damage.</p><p>Because our pricing is flat-rate, you'll never pay extra for nights, weekends, or holidays. <a href='/contact'>Save our number</a> so you're ready before an emergency strikes.</p><p>A tip from our dispatchers: find your main water shutoff now, before you need it. It's usually where the service line enters the house — basement front wall, crawl space, or near the water heater. Knowing those thirty seconds of geography can save thousands in drywall and flooring when a pipe lets go.</p>"],
            ['type' => 'image', 'heading' => 'Licensed Guardian Air plumber repairing pipes in a New Jersey home', 'image_path' => '/img/plumbing-hero.webp'],
            ['type' => 'section', 'heading' => 'Water Heater Repair & Replacement', 'body' => "<p>No hot water is one of the most common reasons New Jersey homeowners call a plumber — and one we solve every day. We repair, replace, and install both tank and <a href='/plumbing/tankless-water-heater'>tankless water heaters</a> from every major brand.</p><p>If your unit is leaking, making popping noises, or running out of hot water, we'll advise whether a repair or a new unit is smarter — see typical costs in our <a href='/cost-guides/plumber-cost'>plumber cost guide</a>. Full details are on our <a href='/plumbing/water-heater'>water heater service</a> page.</p><p>Thinking about going tankless? We'll explain the benefits — endless hot water, lower bills, and a smaller footprint — and help you <a href='/contact'>choose the right system</a> for your home and budget.</p><p>Sediment is the quiet killer of New Jersey water heaters — our moderately hard water settles a mineral layer on the tank floor that insulates the burner from the water, wasting fuel and stressing the steel. An annual flush costs little and routinely adds years; ask us to show you how, or bundle it with any service visit.</p>"],
            ['type' => 'section', 'heading' => 'Leak Detection & Pipe Repair', 'body' => "<p>A hidden leak can quietly cause thousands in water damage before you see a drip. Our plumbers use professional <a href='/plumbing/leak-detection'>leak detection</a> to pinpoint the exact source behind walls, under floors, and in slabs — no demolition guesswork.</p><p>Hidden leaks leave clues: a water bill creeping up month over month, faint hissing in quiet rooms, stained ceilings or warped flooring, weak fixture pressure, or a musty odor that may also call for <a href='/indoor-air-quality/mold-testing'>mold testing</a>.</p><p>From a single corroded section to a full home repipe, we replace aging pipes common in older homes across <a href='/service-areas'>central New Jersey</a> with modern, long-lasting materials.</p><p>One overlooked culprit: water pressure. Municipal pressure above 80 PSI strains every joint, valve, and supply hose in the house, and it's common in parts of our service area. We measure static pressure on leak calls and can install or adjust a pressure-reducing valve to take the load off your whole system.</p>"],
            ['type' => 'section', 'heading' => 'Plumber in Toms River, Brick & Ocean County', 'body' => "<p>Guardian Air is a trusted local plumber throughout Ocean County, NJ. Our plumbers serve <a href='/plumbing/toms-river'>Toms River</a>, <a href='/plumbing/brick'>Brick</a>, Lakewood, and the surrounding shore communities with fast response times and honest, flat-rate pricing.</p><p>From <a href='/plumbing/water-heater'>water heater replacements</a> in Toms River to emergency leak detection in Brick, our licensed team handles it all. See our full <a href='/plumbing/ocean-county'>Ocean County plumbing</a> coverage — because we're local, help is never far away.</p><p>Shore-area plumbing has its own rhythms: seasonal homes that need winterizing and spring start-ups, salt-air corrosion on outdoor fixtures, and crawl-space pipes that freeze in onshore winds. Our Ocean County crews handle those calls all year.</p>"],
            ['type' => 'section', 'heading' => 'Plumber in Freehold & Monmouth County', 'body' => "<p>Across Monmouth County, homeowners in <a href='/plumbing/freehold'>Freehold</a>, Red Bank, and the surrounding area rely on Guardian Air for dependable plumbing service. We also serve Old Bridge and the rest of <a href='/plumbing/middlesex-county'>Middlesex County</a>.</p><p>From routine repairs to <a href='/plumbing/emergency-plumber'>24/7 emergencies</a>, our licensed plumbers deliver the same upfront pricing on every job. Browse all our <a href='/service-areas'>service areas</a> — don't see your town? We almost certainly still serve it, so give us a call today.</p>"],
            ['type' => 'section', 'heading' => 'Serving Monmouth, Middlesex & Ocean County', 'body' => "<p>From Sayreville to Seaside, our plumbing trucks cover the full three-county footprint every day. That density is what makes same-day service realistic: a plumber finishing a job in Howell can be at your door in Lakewood within the hour, not tomorrow morning.</p><p>We schedule in tight arrival windows, call ahead when the technician is en route, and confirm the flat-rate price before any wrench turns — the same process at every address we serve, from <a href='/plumbing/middlesex-county'>Middlesex County</a> commuter towns to the <a href='/plumbing/ocean-county'>Ocean County</a> shore.</p>"],
            ['type' => 'faq', 'heading' => 'How much does an emergency plumber cost in NJ?', 'body' => 'Expect roughly $150 for a simple after-hours fix up to $500 or more when major parts are involved. The number you approve before work starts is the number you pay — Guardian Air never adds night, weekend, or holiday surcharges.'],
            ['type' => 'faq', 'heading' => 'Do you offer 24-hour plumbing service in Monmouth County?', 'body' => 'Yes. We provide 24-hour emergency plumbing across Monmouth County, including Freehold, Red Bank, Middletown, and Howell. Call any time and we\'ll dispatch a licensed plumber as quickly as possible to stop the damage and fix the problem.'],
            ['type' => 'faq', 'heading' => 'What are the signs of a slab leak?', 'body' => 'A slab leak often announces itself indirectly: a water heater that runs constantly, a warm patch underfoot, hairline cracks in tile, or a bill that jumps with no change in habits. Acoustic and thermal equipment lets us confirm and pinpoint it without tearing up the floor.'],
            ['type' => 'faq', 'heading' => 'Can you repair a tankless water heater?', 'body' => 'Yes. We repair and maintain tankless water heaters from all major brands — addressing error codes, scale buildup, ignition issues, and flow problems. If a unit is beyond economical repair, we\'ll recommend and install a reliable replacement.'],
            ['type' => 'faq', 'heading' => 'What plumbing services do you offer in Toms River?', 'body' => 'In Toms River and the surrounding Ocean County area we offer the full range of residential plumbing: emergency repairs, water heater repair and replacement, leak detection, pipe repair and repiping, drain cleaning, and fixture installation — all with flat-rate pricing.'],
        ];
    }

    private function electrical(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Electrical Service Overview', 'body' => "Electrical work is not a DIY project. Whether you need a panel upgrade to handle modern appliances, new outlets for a home office, or emergency repairs for a tripped breaker, our licensed electricians deliver safe, code-compliant work every time.\n\nWe handle residential and light commercial electrical projects of all sizes. Every job starts with a thorough inspection and a flat-rate quote. We explain what needs to be done, why it matters for your safety, and what it will cost — before we touch a single wire."],
            ['type' => 'section', 'heading' => 'Why Electrical Safety Matters', 'body' => "Your home's electrical system powers everything you rely on, and when it's neglected, the risks add up fast. Staying on top of it protects your home and your family.\n\nPrevent Electrical Fires — Faulty wiring and overloaded circuits are a leading cause of home fires. Regular inspections catch hidden hazards before they become dangerous.\n\nProtect Your Appliances — Proper wiring and surge protection shield your electronics and appliances from damaging power spikes, extending their lifespan.\n\nStay Code-Compliant — Outdated or DIY wiring can fail inspection and void insurance. Licensed work keeps your home up to current electrical code and safe for your family."],
            ['type' => 'image', 'heading' => 'Guardian Air electrician working on a residential electrical panel in New Jersey', 'image_path' => '/img/electrical.webp'],
            ['type' => 'section', 'heading' => 'Signs You Need An Electrician', 'body' => "Electrical problems rarely fix themselves. Watch for these warning signs that it's time to call a licensed pro.\n\nFrequent Tripping — Breakers that trip repeatedly or fuses that blow often signal an overloaded circuit or a wiring fault that needs professional attention.\n\nFlickering or Dimming Lights — Lights that flicker or dim when appliances turn on point to loose connections, an overloaded panel, or aging wiring.\n\nWarm Outlets or Burning Smell — Outlets or switches that feel warm, spark, or give off a burning odor are serious fire hazards. Shut off the circuit and call us right away.\n\nOutdated Panel or Wiring — Homes with a fuse box, aluminum wiring, or a panel under 100 amps often can't safely handle modern electrical demands.\n\nNoticing any of these in your home? Schedule an electrical inspection and we'll get to the root of it."],
            ['type' => 'section', 'heading' => 'Electrical Services We Offer', 'body' => "Here's a quick guide to the electrical work we install, repair, and maintain.\n\nPanel Upgrades — Modernize your electrical panel to safely handle today's appliances, EV chargers, and high-demand circuits with confidence.\n\nWiring & Rewiring — New circuits, full-home rewires, and repairs to damaged or outdated wiring, all done to current code for lasting safety.\n\nLighting & Fixtures — Recessed lighting, ceiling fans, outdoor and accent fixtures installed cleanly to brighten and elevate every room.\n\nOutlets & Switches — New outlets, GFCI installations, dimmers, and smart switches added wherever you need safe, convenient power.\n\nGenerators & EV Chargers — Standby generator hookups and Level 2 EV charger installs that keep you powered and ready for the future."],
            ['type' => 'faq', 'heading' => 'How do I know if my electrical panel needs an upgrade?', 'body' => 'If you have a fuse box, a panel rated under 100 amps, frequently tripping breakers, or you\'re adding major appliances or an EV charger, it\'s likely time for an upgrade. We can assess your panel and recommend the right capacity for your home.'],
            ['type' => 'faq', 'heading' => 'Why do my circuit breakers keep tripping?', 'body' => 'Repeated tripping usually means a circuit is overloaded, or there\'s a short circuit or ground fault. It\'s the breaker doing its job, but persistent tripping points to an underlying issue a licensed electrician should diagnose.'],
            ['type' => 'faq', 'heading' => 'Is it safe to do my own electrical work?', 'body' => 'Swapping a light bulb or resetting a tripped breaker is fine. Anything involving wiring, outlets, panels, or new circuits should be left to a licensed electrician — DIY electrical mistakes can cause fires, shocks, and failed inspections.'],
            ['type' => 'faq', 'heading' => 'What causes flickering or dimming lights?', 'body' => 'Flickering often comes from loose wiring, an overloaded circuit, a failing fixture, or a panel that can\'t keep up with demand. If it happens throughout the house, it\'s worth having the system inspected.'],
            ['type' => 'faq', 'heading' => 'Why do my outlets feel warm or spark?', 'body' => 'A warm outlet, sparking, or a burning smell signals loose connections, overloading, or damaged wiring, all serious fire risks. Stop using the outlet, turn off the circuit, and call us for same-day service.'],
            ['type' => 'faq', 'heading' => 'What is a GFCI outlet and where do I need them?', 'body' => 'A GFCI (Ground Fault Circuit Interrupter) outlet shuts off power instantly if it detects a fault, preventing shocks. Code requires them in kitchens, bathrooms, garages, basements, and outdoor areas.'],
            ['type' => 'faq', 'heading' => 'Can you install an EV charger at my home?', 'body' => 'Yes. We install Level 2 EV chargers, including any panel upgrades or dedicated circuits needed to support them safely. We\'ll evaluate your panel capacity and recommend the best setup for your vehicle.'],
            ['type' => 'faq', 'heading' => 'Do I need a permit for electrical work?', 'body' => 'Most electrical work — panel upgrades, new circuits, and rewiring — requires a permit and inspection. As licensed electricians, we handle the permitting process and ensure every job passes inspection.'],
            ['type' => 'faq', 'heading' => "How often should I have my home's wiring inspected?", 'body' => "We recommend an inspection every few years for newer homes, and sooner for homes over 25 years old or any home you've just purchased. Aluminum wiring and older panels should be checked promptly."],
            ['type' => 'faq', 'heading' => 'What should I do during an electrical emergency?', 'body' => 'If you smell burning, see sparks, or have exposed wiring, shut off power at the breaker if it\'s safe to do so and keep away from the area. Then call us — we offer same-day emergency electrical service.'],
        ];
    }

    private function airQuality(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Air Quality Testing NJ', 'body' => "<p>If your family is dealing with constant dust, allergies, or musty odors, professional air quality testing in NJ is the first step to a healthier home. Guardian Air serves homeowners across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a> — we test, diagnose, and fix the air you breathe.</p><p>The air inside your home can be up to five times more polluted than outside. Dust, pollen, dander, mold spores, and VOCs all circulate through your HVAC system. We assess your home and recommend the right mix of filtration, humidity control, and purification — and may suggest <a href='/indoor-air-quality/mold-testing'>mold testing</a> when moisture is involved.</p><p>From whole-home <a href='/indoor-air-quality/air-purifier'>air purifiers</a> and UV lights to <a href='/indoor-air-quality/duct-cleaning'>air duct cleaning</a>, we have a solution for every concern and budget.</p><p>A proper assessment measures rather than guesses: particulate counts, relative humidity, carbon dioxide buildup from poor ventilation, and a visual inspection of the duct system and filtration. The result is a prioritized plan — what's actually in your air, which fix moves the needle most, and what can safely wait.</p>"],
            ['type' => 'section', 'heading' => 'Signs of Poor Air Quality', 'body' => "<p>Poor indoor air quality isn't always obvious. Watch for these warning signs — and <a href='/contact'>schedule an assessment</a> if you notice them.</p><p><strong>Persistent Dust</strong> — If dust resettles right after cleaning, your air is full of fine particles that <a href='/indoor-air-quality/duct-cleaning'>duct cleaning</a> and better filtration help remove.</p><p><strong>Allergy & Respiratory Symptoms</strong> — Sneezing, congestion, or irritated eyes indoors point to pollen and dander an <a href='/indoor-air-quality/air-purifier'>air purifier</a> can capture.</p><p><strong>Musty or Stale Odors</strong> — Lingering smells can signal mold or moisture that calls for <a href='/indoor-air-quality/mold-testing'>mold testing</a>.</p><p><strong>Humidity Problems</strong> — Condensation, clammy air, or overly dry air mean your home needs <a href='/indoor-air-quality/humidifier-dehumidifier'>humidity control</a>.</p><p>Symptoms that ease when you leave the house are the classic tell: if congestion, headaches, or itchy eyes improve at work or on vacation and return within hours of walking back in, the trigger is likely circulating through your HVAC system rather than drifting in from outside. Black dust rings around supply vents and condensation on winter windows point the same direction.</p>"],
            ['type' => 'image', 'heading' => 'Guardian Air technician performing indoor air quality testing in a New Jersey home', 'image_path' => '/img/air-quality-hero.webp'],
            ['type' => 'section', 'heading' => 'Air Quality Solutions for NJ Homes', 'body' => "<p>Based on your testing results, we install and service the full range of indoor air quality solutions across <a href='/service-areas'>New Jersey</a>.</p><p><strong>Air Purifiers</strong> — Whole-home <a href='/indoor-air-quality/air-purifier'>air purifier</a> systems that capture allergens, dust, smoke, and microscopic particles.</p><p><strong>Mold Testing & Guidance</strong> — We identify hidden moisture and mold with <a href='/indoor-air-quality/mold-testing'>mold testing</a> and lay out a clear plan to resolve it.</p><p><strong>Duct Cleaning</strong> — <a href='/indoor-air-quality/duct-cleaning'>Air duct cleaning</a> clears built-up dust and allergens so every room breathes cleaner.</p><p><strong>Humidifiers & Dehumidifiers</strong> — <a href='/indoor-air-quality/humidifier-dehumidifier'>Whole-home humidity control</a> that ends dry winter air and damp, clammy summers in one install.</p><p>Sequence matters when combining solutions: clean the ducts before upgrading filtration so the new media isn't loading up on old debris, and address moisture before installing UV so the lamps aren't fighting a losing battle. We stage multi-part projects in the order that protects each investment.</p>"],
            ['type' => 'section', 'heading' => 'Why NJ Homes Need IAQ', 'body' => "<p>New Jersey's humid summers and tightly sealed winters create the perfect conditions for poor indoor air quality — which is why <a href='/indoor-air-quality/duct-cleaning'>duct cleaning</a> and filtration pay off every day.</p><p><strong>Protect Your Health</strong> — Cleaner air reduces the allergens and irritants that aggravate asthma and allergies; an <a href='/indoor-air-quality/air-purifier'>air purifier</a> helps most.</p><p><strong>Breathe Easier Every Day</strong> — Balanced <a href='/indoor-air-quality/humidifier-dehumidifier'>humidity</a> and proper filtration help your family sleep better and feel more comfortable.</p><p><strong>Protect Your Home & HVAC</strong> — Controlling dust and moisture keeps your <a href='/heating'>HVAC system</a> efficient and helps prevent mold damage.</p><p>Newer homes aren't exempt — tighter construction traps cooking byproducts, VOCs from furnishings, and humidity that older, draftier houses used to vent by accident. Mechanical ventilation and filtration do deliberately what leaky walls once did accidentally, and pollen-heavy springs, humid summers, and sealed-up winters each load the air differently through the year.</p>"],
            ['type' => 'section', 'heading' => 'Serving Monmouth, Middlesex & Ocean County', 'body' => "<p>Guardian Air provides indoor air quality testing and solutions to homeowners throughout central New Jersey. Because our technicians are local, we understand the seasonal humidity, pollen, and older-home conditions that affect air quality across the region.</p><p>Our IAQ technicians cover <a href='/indoor-air-quality/toms-river'>Toms River</a>, <a href='/indoor-air-quality/freehold'>Freehold</a>, and every town between the shore and the Raritan — if you're in one of our three counties, you're in range.</p><p>Explore our specific solutions — <a href='/indoor-air-quality/duct-cleaning'>air duct cleaning</a>, <a href='/indoor-air-quality/mold-testing'>mold testing</a>, and air purifiers. Don't see your town listed? We almost certainly still serve it — call to schedule your air quality assessment today.</p><p>Assessments are typically scheduled within a few days, and most solution installs take a single visit. If you're weighing options for a specific concern — allergies, odors, dust, humidity — mention it when you book so we send the right specialist with the right instruments.</p>"],
            ['type' => 'faq', 'heading' => 'How much does air quality testing cost in NJ?', 'body' => 'Indoor air quality assessments in New Jersey typically range from a complimentary visual evaluation to a few hundred dollars for detailed testing of particulates, humidity, and contaminants. We explain your options upfront and recommend only what your home actually needs.'],
            ['type' => 'faq', 'heading' => 'What are the most common indoor air pollutants in NJ homes?', 'body' => 'The most common culprits are dust, pollen, pet dander, mold spores, and volatile organic compounds (VOCs) from cleaning products and building materials. New Jersey\'s humid summers also encourage mold and dust mites, while tightly sealed winters trap pollutants indoors.'],
            ['type' => 'faq', 'heading' => 'Does my HVAC filter really affect air quality?', 'body' => 'Yes — significantly. A clogged or low-grade filter lets fine particles recirculate through your home. Most filters should be changed every one to three months, and upgrading to a higher-efficiency (higher-MERV) filter can noticeably improve the air, as long as your system is rated for it.'],
            ['type' => 'faq', 'heading' => 'What is the best air purifier for a whole house?', 'body' => 'For whole-home coverage, a media air purifier or UV-equipped system installed directly into your HVAC ductwork outperforms portable units because it treats all the air your system moves. We size the right solution based on your home and specific air quality concerns.'],
            ['type' => 'faq', 'heading' => 'What is the ideal indoor humidity level?', 'body' => 'Aim for 30–50% relative humidity. Below that range you get static shocks, dry sinuses, and gapping hardwood floors; above it, condensation, dust mites, and mold gain a foothold. A whole-home unit holds the sweet spot automatically.'],
        ];
    }

    private function drains(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Drain Cleaning Services in NJ', 'body' => "<p>Need fast, reliable drain cleaning in NJ? Guardian Air is a licensed and insured drain and sewer company serving homeowners across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a>. A backed-up line can damage your home, so we clear it completely instead of punching a temporary hole through the clog.</p><p>When needed, we start with a <a href='/drains/camera-inspection'>camera inspection</a> to see the real cause, then use the right tool — from motorized snaking to hydro jetting. Every job comes with upfront, flat-rate pricing — see our <a href='/cost-guides/drain-cleaning-cost'>drain cleaning cost guide</a>.</p><p>What you pour matters less than what cools inside the pipe: grease that flows in hot congeals twenty feet down the line, where no plunger reaches. And skip the caustic store-bought openers — they damage older pipes, rarely clear the real blockage, and make the eventual professional visit more hazardous.</p>"],
            ['type' => 'section', 'heading' => 'Signs of a Drain Problem', 'body' => "<p>Catching a drain issue early saves you from a messy, expensive backup — <a href='/contact'>schedule service</a> at the first warning sign.</p><p><strong>Slow Drainage</strong> — Water that pools and drains slowly is the earliest sign of a developing clog we can clear with <a href='/drains'>drain cleaning</a>.</p><p><strong>Gurgling Sounds</strong> — Bubbling noises mean air is trapped behind a blockage; a <a href='/drains/camera-inspection'>camera inspection</a> locates it.</p><p><strong>Foul Odors</strong> — Persistent sewage smells usually point to trapped debris or a partial blockage that may need <a href='/drains/hydro-jetting'>hydro jetting</a>.</p><p><strong>Frequent Clogs</strong> — If you're plunging the same drain repeatedly, the real problem is deeper in the line and may call for <a href='/drains/sewer-repair'>sewer repair</a>.</p><p><strong>Water in the Lowest Fixture</strong> — Water rising in a basement floor drain or first-floor tub while other fixtures run is the house's bottleneck announcing itself. Stop running water and call promptly.</p>"],
            ['type' => 'image', 'heading' => 'Guardian Air technician performing drain cleaning in a New Jersey home', 'image_path' => '/img/drains-hero.webp'],
            ['type' => 'section', 'heading' => 'Drain Cleaning in Monmouth & Middlesex County', 'body' => "<p>Guardian Air provides trusted drain cleaning throughout Monmouth and Middlesex counties. Homeowners in <a href='/drains/freehold'>Freehold</a>, <a href='/drains/red-bank'>Red Bank</a>, and Old Bridge rely on us for fast, clean drain and sewer service — as do families across Toms River, Brick, and Lakewood.</p><p>From a clogged kitchen sink to a backed-up main line needing <a href='/drains/hydro-jetting'>hydro jetting</a> or <a href='/drains/sewer-repair'>sewer repair</a>, our local technicians clear it the first time. Browse all our service areas — help is never far away when a drain emergency strikes.</p><p>Worth knowing: the township sewer main and your private lateral meet at the curb, and responsibility splits there. If our camera shows the blockage sits on the utility's side, we'll tell you plainly — the township clears that for free, and you shouldn't pay us to try.</p>"],
            ['type' => 'section', 'heading' => 'Sewer Repair & Line Replacement', 'body' => "<p>A failing sewer line causes repeat backups, foul odors, and serious health hazards. From spot repairs to full line replacement, our <a href='/drains/sewer-repair'>sewer repair</a> service fixes cracked, collapsed, and root-invaded lines and restores reliable flow.</p><p>Tree roots are a common culprit in older neighborhoods across <a href='/service-areas'>New Jersey</a>. A <a href='/drains/camera-inspection'>camera inspection</a> confirms the issue so we recommend the right repair, not a guess.</p><p>Our quotes separate the must from the maybe: a cracked joint at thirty feet doesn't obligate you to replace the whole run, and we'll say so even when the bigger job pays more.</p>"],
            ['type' => 'section', 'heading' => 'Hydro Jetting', 'body' => "<p>Our <a href='/drains/hydro-jetting'>hydro jetting</a> service uses high-pressure water to scour the inside of your pipes clean — blasting away grease, scale, and roots that snaking leaves behind. It's the most thorough fix for stubborn and recurring clogs.</p><p>If you find yourself clearing the same drain again and again, hydro jetting restores the line to like-new flow — and our <a href='/cost-guides/drain-cleaning-cost'>cost guide</a> shows what to expect.</p>"],
            ['type' => 'section', 'heading' => 'Camera Inspection', 'body' => "<p>A waterproof <a href='/drains/camera-inspection'>camera inspection</a> travels through your line so you can see the exact cause and location of a problem — no demolition guesswork.</p><p>We use it to diagnose chronic clogs, locate breaks and root intrusion, and verify the line is clear after <a href='/drains/sewer-repair'>sewer repair</a> — the smartest way to confirm what's happening before spending money.</p>"],
            ['type' => 'section', 'heading' => 'Emergency Drain Service', 'body' => "<p>When a main line backs up or a drain floods, it can't wait. Guardian Air offers same-day and 24/7 emergency drain service across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a>.</p><p>Call and you'll reach a real person who dispatches a technician fast to clear the blockage and protect your home — at the same flat rate, day or night. <a href='/contact'>Schedule service</a> now.</p><p>Holiday weekends are our busiest stretch — extra cooking, extra guests, extra strain on the kitchen line. Crews stay staffed through them at the same flat rate, so a Thanksgiving backup doesn't wait for Monday.</p>"],
            ['type' => 'section', 'heading' => 'Serving Monmouth, Middlesex & Ocean County', 'body' => "<p>Drain trucks are based across the three counties, so a clogged kitchen line in New Brunswick and a main-line backup in Barnegat both get same-day attention. Jetting and camera rigs travel with the crew — no second appointment just to finish the diagnosis.</p><p>Whatever your town, the process is identical: a clear description of the problem, a flat-rate price approved before work starts, and a clean job site when we leave.</p>"],
            ['type' => 'faq', 'heading' => 'How much does drain cleaning cost in NJ?', 'body' => 'Most drain cleaning in New Jersey ranges from about $150 to $500 depending on the location and severity of the clog, with hydro jetting on the higher end. We provide a flat-rate quote upfront with no hidden fees, so you know the cost before we start.'],
            ['type' => 'faq', 'heading' => 'What are the signs I need a sewer line replacement?', 'body' => 'Repeated backups at the lowest drain in the house, several fixtures clogging together, sewage smells indoors or out, and lush wet stripes in the lawn all suggest the main line is failing. Camera footage tells us whether a spot repair will hold or the run needs replacing.'],
            ['type' => 'faq', 'heading' => 'Why do my drains keep clogging?', 'body' => 'Chronic clogs are usually caused by grease buildup, hair, soap scum, mineral scale, or tree roots in the main line. A one-time clearing may not solve a deeper issue, so we inspect the line to find and fix the real cause — often with hydro jetting.'],
            ['type' => 'faq', 'heading' => 'Do you offer emergency drain service in Monmouth County?', 'body' => 'We do — drain and sewer emergencies get same-day dispatch throughout Monmouth County, from Middletown and Howell to the Freehold area, at our standard flat rate around the clock.'],
            ['type' => 'faq', 'heading' => 'Is hydro jetting better than snaking?', 'body' => 'Snaking is great for breaking through a single clog quickly, while hydro jetting cleans the entire interior of the pipe, removing grease, scale, and roots. For recurring or severe clogs, hydro jetting delivers a more thorough, longer-lasting result.'],
        ];
    }

    private function commercial(): array
    {
        return [
            ['type' => 'section', 'heading' => 'Commercial HVAC Repair & Emergency', 'body' => "<p>When your commercial HVAC system fails on a 95-degree day, every minute of downtime costs money. Businesses that need commercial HVAC in NJ call Guardian Air for fast <a href='/commercial-hvac/repair'>commercial HVAC repair</a> across <a href='/service-areas'>Monmouth, Middlesex, and Ocean counties</a>.</p><p>Our technicians repair rooftop units (RTUs), boilers, chillers, and split systems of every size. We're available 24/7, and <a href='/commercial-hvac/maintenance-contracts'>maintenance-plan clients</a> receive priority dispatch — in most cases a technician on-site the same day.</p><p>Every call starts with a clear diagnosis and a written quote, so there are no surprises — just honest commercial service. <a href='/contact'>Request service</a> any time.</p><p>We track response by the numbers that matter to a business: time to arrival, first-visit resolution, and whether the space stayed open. Dispatch knows which clients run kitchens, server rooms, or refrigerated stock, and routes accordingly.</p>"],
            ['type' => 'section', 'heading' => 'Commercial HVAC Installation', 'body' => "<p>Whether you're outfitting a new build, replacing an aging rooftop unit, or upgrading to high-efficiency, our team handles commercial HVAC installation from load calculation to startup across <a href='/service-areas'>New Jersey</a>.</p><p>We properly size every system to your facility's square footage and usage — an undersized unit struggles and an oversized one wastes energy. Protect that investment with a <a href='/commercial-hvac/maintenance-contracts'>maintenance contract</a> after install.</p><p>We coordinate around your business hours and handle permitting and code compliance. <a href='/contact'>Get a free assessment</a> for your facility.</p><p>Replacement planning works best a season ahead: lead times on commercial rooftop units run weeks, and crane scheduling adds more. If your unit is past fifteen years, a fall assessment lets you replace on your calendar instead of during a July failure.</p>"],
            ['type' => 'image', 'heading' => 'Guardian Air commercial technician servicing a rooftop HVAC unit in New Jersey', 'image_path' => '/img/commercial-hero.webp'],
            ['type' => 'section', 'heading' => 'Preventive Maintenance Contracts', 'body' => "<p>For a business, unexpected equipment failure means lost revenue. A scheduled <a href='/commercial-hvac/maintenance-contracts'>preventive maintenance contract</a> protects your operation and your bottom line.</p><p><strong>Reduce Costly Downtime</strong> — Scheduled inspections catch small failures early, before they shut you down during peak hours and force an <a href='/commercial-hvac/repair'>emergency repair</a>.</p><p><strong>Lower Operating Costs</strong> — Well-maintained systems run more efficiently, cutting energy bills across your <a href='/service-areas'>NJ</a> locations.</p><p><strong>Protect Your Investment</strong> — Routine service extends the life of rooftop units, boilers, and chillers, and keeps warranties valid. <a href='/contact'>Ask about a plan</a> for your equipment.</p><p>Budgeting is the quiet benefit: a fixed annual contract price plus documented equipment condition turns HVAC from a surprise line item into a forecastable one — something owners and property managers both appreciate at renewal time.</p>"],
            ['type' => 'section', 'heading' => 'Industries We Serve', 'body' => "<p>We tailor our <a href='/commercial-hvac'>commercial HVAC</a> and <a href='/commercial-plumbing'>plumbing</a> service to the unique demands of each type of facility.</p><p><strong>Offices & Professional Buildings</strong> — Consistent comfort for tenants and staff, with discreet scheduling backed by a <a href='/commercial-hvac/maintenance-contracts'>maintenance plan</a>.</p><p><strong>Restaurants & Food Service</strong> — Make-up air, refrigeration, and rooftop service that meets health-code standards — plus fast <a href='/commercial-hvac/repair'>repair</a> when the kitchen can't stop.</p><p><strong>Retail & Shopping Centers</strong> — Reliable heating and cooling across <a href='/service-areas'>central NJ</a> that keeps customers comfortable.</p><p><strong>Multi-Family & Property Management</strong> — Building-wide HVAC maintenance with fast response — <a href='/contact'>tell us about your property</a>.</p><p><strong>Houses of Worship & Schools</strong> — Large, intermittently occupied spaces with aging equipment; we tune zoning and schedules so comfort arrives before the crowd does, without conditioning empty rooms all week.</p>"],
            ['type' => 'section', 'heading' => 'Commercial Boiler & Heating', 'body' => "<p>Larger facilities depend on commercial boilers that can't fail in a New Jersey winter. We service, repair, and replace hydronic and steam boilers, rooftop heating units, and make-up air systems — book it through <a href='/commercial-hvac/repair'>commercial HVAC repair</a>.</p><p>From pressure and leak diagnostics to full boiler replacement, our technicians keep your building warm and efficient. We also handle <a href='/commercial-plumbing'>commercial plumbing</a> sized for a busy property.</p><p>Regular maintenance keeps your heat reliable and costs down — see our <a href='/commercial-hvac/maintenance-contracts'>maintenance contracts</a>.</p><p>Steam and hydronic plants in older commercial buildings reward specialist attention: balancing risers in mixed-use properties, staging multiple boilers for efficiency, and keeping make-up air from fighting the heating plant. We document setpoints and sequences so the building runs the same way after every visit.</p>"],
            ['type' => 'section', 'heading' => 'Serving Businesses in Monmouth, Middlesex & Ocean County', 'body' => "<p>Guardian Air serves commercial clients throughout central New Jersey, including <a href='/commercial-hvac/toms-river'>Toms River</a>, <a href='/commercial-hvac/freehold'>Freehold</a>, and Brick, plus all of Monmouth, Middlesex, and Ocean counties. Because our technicians are local, we respond fast when your business needs us.</p><p>Our team is licensed and insured for commercial work, NATE-certified, and EPA 608 certified for refrigerant handling — the B2B credentials property managers expect. Explore our <a href='/commercial-hvac/maintenance-contracts'>maintenance contracts</a>, <a href='/commercial-hvac/repair'>emergency repair</a>, and commercial plumbing. You get code-compliant work, documented service, and a single point of contact for scheduling and billing.</p>"],
            ['type' => 'faq', 'heading' => 'Do you offer commercial HVAC maintenance contracts?', 'body' => 'Yes. We build custom preventive maintenance contracts with scheduled visits, priority response, and detailed service records — tailored to your equipment and budget so problems get caught before they become emergencies.'],
            ['type' => 'faq', 'heading' => 'What commercial HVAC systems do you service?', 'body' => 'We install, repair, and maintain packaged rooftop units (RTUs), split and ductless systems, commercial boilers (hydronic and steam), and chillers, plus commercial plumbing. We service all major brands across offices, restaurants, retail, and multi-family properties.'],
            ['type' => 'faq', 'heading' => 'How quickly can you respond to a commercial HVAC emergency?', 'body' => 'Our team is available 24/7 for commercial HVAC emergencies. Maintenance-contract clients receive priority dispatch, and in most cases we can have a licensed technician on-site the same day across Monmouth, Middlesex, and Ocean counties.'],
            ['type' => 'faq', 'heading' => 'Do you service restaurants and retail in Monmouth County?', 'body' => 'Yes. We work with restaurants, retail stores, and shopping centers throughout Monmouth County — including Freehold, Red Bank, and Middletown — handling rooftop units, make-up air, and refrigeration with scheduling that keeps your doors open for business.'],
            ['type' => 'faq', 'heading' => 'How much does a commercial HVAC maintenance contract cost?', 'body' => 'Pricing depends on the number and type of units, visit frequency, and facility size, so we quote each plan individually. Most clients find a preventive contract pays for itself by avoiding emergency repairs and downtime. We provide a clear, written proposal upfront.'],
        ];
    }
}
